import json
import urllib.request
import urllib.error
from openai import OpenAI
from app.config import settings

SYSTEM_PROMPT = """You are a highly precise enterprise knowledge assistant.
Your task is to answer the user's question using ONLY the provided context blocks.

Instructions:
1. Support all claims with citations to the document name and page number.
2. Use the format [Source: filename, Page: number] (for example, [Source: employee_handbook.pdf, Page: 3]) at the end of the sentence or block where you state that information.
3. If the context does not contain enough information to answer, state clearly: "I cannot answer this question based on the uploaded documents." Do not try to make up or extrapolate facts.
4. Keep your responses factual, objective, and clear. Format the response with markdown (lists, bold text) for readability.
"""

def generate_answer_from_llm(query: str, context: str) -> str:
    """
    Routes the query and context to the appropriate LLM provider (OpenAI, Google Gemini, or Groq).
    """
    provider = settings.LLM_PROVIDER.lower()
    
    prompt = f"Context:\n{context}\n\nQuestion: {query}"
    
    if provider == "google":
        if not settings.GOOGLE_API_KEY:
            return "Error: GOOGLE_API_KEY is not set in the environment variables."
        return call_gemini(settings.GOOGLE_API_KEY, settings.GOOGLE_MODEL, prompt, SYSTEM_PROMPT)
    
    elif provider == "openai":
        if not settings.OPENAI_API_KEY:
            return "Error: OPENAI_API_KEY is not set in the environment variables."
        return call_openai(settings.OPENAI_API_KEY, settings.OPENAI_MODEL, prompt, SYSTEM_PROMPT)
    
    elif provider == "groq":
        if not settings.GROQ_API_KEY:
            return "Error: GROQ_API_KEY is not set in the environment variables."
        return call_groq(settings.GROQ_API_KEY, settings.GROQ_MODEL, prompt, SYSTEM_PROMPT)
    
    else:
        return f"Error: Unsupported LLM Provider: {provider}. Choose 'openai', 'google', or 'groq'."


def call_openai(api_key: str, model: str, prompt: str, system_prompt: str) -> str:
    try:
        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error calling OpenAI API: {e}"


def call_groq(api_key: str, model: str, prompt: str, system_prompt: str) -> str:
    try:
        # Use Groq's OpenAI-compatible API endpoint
        client = OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error calling Groq API: {e}"


def call_gemini(api_key: str, model: str, prompt: str, system_prompt: str) -> str:
    """Calls Google Gemini using the standard REST API to avoid SDK version conflicts."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "systemInstruction": {
            "parts": [{"text": system_prompt}]
        },
        "generationConfig": {
            "temperature": 0.1
        }
    }
    
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            candidates = res_data.get("candidates", [])
            if candidates:
                parts = candidates[0].get("content", {}).get("parts", [])
                if parts:
                    return parts[0].get("text", "")
            return "Error: No response generated by Gemini."
            
    except urllib.error.HTTPError as e:
        error_content = e.read().decode("utf-8")
        try:
            error_json = json.loads(error_content)
            error_msg = error_json.get("error", {}).get("message", error_content)
        except Exception:
            error_msg = error_content
        return f"Gemini API HTTP Error: {e.code} - {error_msg}"
    except Exception as e:
        return f"Error calling Gemini REST API: {e}"
